import React from 'react';
import { Check } from 'lucide-react';
import { AppLink } from '../app/router';

const plans = [
  { name:'Starter', key:'starter', price:'149', description:'Core CRM, lead capture, bookings and basic AI.', features:['CRM + customer history','Lead pipeline','Booking engine','Basic AI assistance','250 SMS allowance target'] },
  { name:'Growth', key:'growth', price:'299', description:'Communication, advanced automations and revenue intelligence.', featured:true, features:['Everything in Starter','Advanced automations','Revenue intelligence','1,000 SMS allowance target','8 team members'] },
  { name:'Operator', key:'operator', price:'599', description:'Full AI Operator and highest automation limits.', features:['Everything in Growth','Full Operator entitlement','Advanced AI actions','4,000 SMS allowance target','25 team members'] },
];

export default function PricingPage() {
  return <div className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><AppLink href="/" className="font-black tracking-tight">JOBRYN</AppLink><div className="flex gap-2"><AppLink href="/login" className="rounded-xl px-4 py-2 text-sm font-semibold text-slate-700">Log in</AppLink><AppLink href="/signup" className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Start free</AppLink></div></div></header><main className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-[.18em] text-indigo-600">Simple SaaS pricing</p><h1 className="mt-3 text-5xl font-black tracking-tight">Pay for the revenue system you need.</h1><p className="mt-5 text-slate-600">Pricing is wired to Stripe Price IDs on the server. Final usage inclusions can be adjusted during beta without changing the security model.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.map(plan=><div key={plan.name} className={`relative rounded-3xl border bg-white p-7 shadow-sm ${plan.featured?'border-indigo-500 ring-4 ring-indigo-500/10':'border-slate-200'}`}>{plan.featured&&<span className="absolute -top-3 left-7 rounded-full bg-indigo-600 px-3 py-1 text-xs font-semibold text-white">Most popular</span>}<h2 className="text-xl font-bold">{plan.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{plan.description}</p><div className="mt-6 flex items-end gap-1"><span className="text-5xl font-black tracking-tight">${plan.price}</span><span className="pb-1.5 text-sm text-slate-500">AUD / month</span></div><AppLink href={`/signup?plan=${plan.key}`} className={`mt-6 block rounded-xl px-4 py-3 text-center text-sm font-semibold ${plan.featured?'bg-indigo-600 text-white':'bg-slate-950 text-white'}`}>Start with {plan.name}</AppLink><div className="mt-6 space-y-3">{plan.features.map(feature=><div key={feature} className="flex gap-2 text-sm text-slate-600"><Check className="mt-0.5 h-4 w-4 flex-none text-emerald-600"/><span>{feature}</span></div>)}</div></div>)}</div></main></div>;
}
