name = "nexus-website"
main = ".open-next/worker.js"
compatibility_date = "2026-03-11"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
account_id = "966a0a7b4cc0406a8301a78e7d00dfe0"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "nexus-website"
